language: node_js
node_js:
  - '12'
install: npm install
script:
  - npm run lint
  - npm test
  - npm run build
notifications:
  email: false
deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  target_branch: gh-pages
  on:
    branch: master
cache:
  directories:
  - node_modules
